### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Lionze0** [Poggicek/mysql_mm#11]
Im having issue with my plugin and this is what my host told me 

You should tell the developer that he uses libssl 1.1 which is End Of Life and should not be used anymore for security reasons

Can u uprage i cant activate the plugin

**Comment by Poggicek** [comment]
a) I don't decide which openssl version to use, the lib version is decided by whatever lib gets linked at compile time. Given I don't provide prebuilt binaries I cannot change that.
b) SteamRT sniper uses openssl 1.1.1w, all metamod plugin should absolutely compile against that environment for maximum compatibility, and all cs2 servers should run under the steamrt environment. Your host seems to be not doing that so they are in the wrong here. Do not expect a change from my side, complain at your host for not following valve [recommendations](https://www.mail-archive.com/csgo_servers@list.valvesoftware.com/msg14291.html).

**Comment by Poggicek** [comment]
May I ask what server host you're using?

**Comment by Lionze0** [comment]
Im using  Vibegames

**Comment by Poggicek** [comment]
right, yeah, those are known to be brain dead

**Comment by Lionze0** [comment]
Haha , is any way to fix thagt problem

**Comment by Poggicek** [comment]
You could try compiling this plugin under the same or close enough gcc version that vibegames uses. I cannot assist you with that however.

**Comment by Lionze0** [comment]
Hm idk what it mean cuz im not an developer , but you cant upgrade the my
sql so it can work?

**Comment by Poggicek** [comment]
I will not provide any precompiled binaries, if you want whatever version you have to work then the host must adjust.

**Comment by Lionze0** [comment]
Ok, thanks for letting me know.

**Comment by Lionze0** [comment]
This is what he said
