### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ghostt187** [Poggicek/mysql_mm#5]
I have been having crashed for 3 days every 1 hour.... tried removing cssharp and every single plugin i had with metamod but i always kept this mysql_mm, until i left server default with nothing on no plugins no nothing and it didnt crash anymore, can u please check whats causing it to crash cuz i really need this plugin

**Comment by Poggicek** [comment]
unless you get a crash dump or any other crash information this isn't actionable

**Comment by ghostt187** [comment]
i have a lot of crash dumps but all of them are when using all the plugins with cssharp too would that help to see why mysql is causing cras?

**Comment by Poggicek** [comment]
a crash dump would help to see if the crash is even induced by mysql_mm at all. I don't see how this plugin could be crashing at all if there's no plugin interfacing with it, especially when bunch of other people are using it just fine

**Comment by ghostt187** [comment]
[55d66a17-5515-4ddc-c76cf2ab-115e69ba.dmp.txt](https://github.com/Poggicek/mysql_mm/files/13762690/55d66a17-5515-4ddc-c76cf2ab-115e69ba.dmp.txt)
this is the latest does this help (the latest since i had on accelerator) .... i know other people are using it thats why i never removed it but once i got it out it stopped crashing thats why its weird

**Comment by ghostt187** [comment]
does metamod version matter? currently using 1256

**Comment by Poggicek** [comment]
> [55d66a17-5515-4ddc-c76cf2ab-115e69ba.dmp.txt](https://github.com/Poggicek/mysql_mm/files/13762690/55d66a17-5515-4ddc-c76cf2ab-115e69ba.dmp.txt) this is the latest does this help (the latest since i had on accelerator) .... i know other people are using it thats why i never removed it but once i got it out it stopped crashing thats why its weird

that crash is not related to mysql_mm

**Comment by ghostt187** [comment]
i have to try maybe using only mysql mm and to see to get a dump from that... its weird cuz since i removed it it has gotten up to 2 hours uptime
