### ISSUE TITLE
COMPILE ERROR

### ISSUE THREAD

**Issue by metacop** [Poggicek/mysql_mm#6]
hl2sdk -> branch cs2

 what is the problem?

echo "export MMSOURCE112=/home/metamod-source" >> ~/.bashrc
echo "export HL2SDKCS2=/home/hl2sdk-root/hl2sdk-cs2" >> ~/.bashrc
. ~/.bashrc
cd build

CC=clang CXX=clang++ python3 ../configure.py -s cs2

![image](https://github.com/Poggicek/mysql_mm/assets/56640826/f548f53e-7b88-4ba2-8b9a-e2953ee78fa6)

ambuild

![image](https://github.com/Poggicek/mysql_mm/assets/56640826/1410f83a-41c1-4a90-8e72-dc447e34d48e)

**Comment by Poggicek** [comment]
I have updated the build process to reflect the new sdk manifests
