### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by himenekocn** [Poggicek/mysql_mm#9]
![IMG_20240317_043058](https://github.com/Poggicek/mysql_mm/assets/9393126/0c55002a-f70d-49c9-8db2-68902c9fbb53)
why it's failed to establish a connection still return true?
@Poggicek

**Comment by himenekocn** [comment]
And it return a mistaken code

**Comment by Poggicek** [comment]
that seems like it is connecting fine but the error code is just broken

**Comment by Poggicek** [comment]
475b399 fixes it
